name: flutter_tindercard
description: Tinder(TanTan) Card Widget, fast way to have a high quality swap card widget in your flutter app.
version: 0.2.0
homepage: https://github.com/ShaunRain/flutter_tindercard

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:
  uses-material-design: true
